spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/granja-mintic
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob,non_contextual_creation: true
  sql.init.platform: postgres
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 96PLeuvseuaGMYafhGd06oH7de9wW8M2
            client-secret: k8oBt0xJmhwx9rSnwWae5bDxBA7Sxkq10-_oNyRke04K3PXuF0RiA3o-GSnIpssw
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-1a5xduuk.us.auth0.com/

springdoc:
  api-docs.enabled: true
  swagger-ui.path:  /swagger-ui